apiVersion: v1
kind: ReplicationController
metadata:
  name: backendrc
  labels:
    app: backend
spec:
  replicas: 1
  selector:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: new_image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        

